// Generated by gencpp from file naoqi_bridge_msgs/HandTouch.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_HANDTOUCH_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_HANDTOUCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct HandTouch_
{
  typedef HandTouch_<ContainerAllocator> Type;

  HandTouch_()
    : hand(0)
    , state(0)  {
    }
  HandTouch_(const ContainerAllocator& _alloc)
    : hand(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _hand_type;
  _hand_type hand;

   typedef uint8_t _state_type;
  _state_type state;


    enum { RIGHT_BACK = 0u };
     enum { RIGHT_LEFT = 1u };
     enum { RIGHT_RIGHT = 2u };
     enum { LEFT_BACK = 3u };
     enum { LEFT_LEFT = 4u };
     enum { LEFT_RIGHT = 5u };
     enum { stateReleased = 0u };
     enum { statePressed = 1u };
 

  typedef boost::shared_ptr< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> const> ConstPtr;

}; // struct HandTouch_

typedef ::naoqi_bridge_msgs::HandTouch_<std::allocator<void> > HandTouch;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::HandTouch > HandTouchPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::HandTouch const> HandTouchConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'naoqi_bridge_msgs': ['/home/jose/medeiros_ws/src/naoqi_bridge_msgs/msg', '/home/jose/medeiros_ws/devel/share/naoqi_bridge_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8d5c81c96dbe6a9e8e5d80beb70299d";
  }

  static const char* value(const ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8d5c81c96dbe6a9ULL;
  static const uint64_t static_value2 = 0xe8e5d80beb70299dULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/HandTouch";
  }

  static const char* value(const ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A message for Nao and Pepper's hand touch interface (touched tactile sensors on the hands)\n\
\n\
uint8 hand            # which hand (left or right)\n\
uint8 state           # state of the hands (pressed or released)\n\
\n\
uint8 RIGHT_BACK=0\n\
uint8 RIGHT_LEFT=1\n\
uint8 RIGHT_RIGHT=2\n\
uint8 LEFT_BACK=3\n\
uint8 LEFT_LEFT=4\n\
uint8 LEFT_RIGHT=5\n\
\n\
uint8 stateReleased=0\n\
uint8 statePressed=1\n\
";
  }

  static const char* value(const ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hand);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HandTouch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::HandTouch_<ContainerAllocator>& v)
  {
    s << indent << "hand: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hand);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_HANDTOUCH_H
