// Generated by gencpp from file naoqi_bridge_msgs/TangentialSecurityDistanceRequest.msg
// DO NOT EDIT!


#ifndef NAOQI_BRIDGE_MSGS_MESSAGE_TANGENTIALSECURITYDISTANCEREQUEST_H
#define NAOQI_BRIDGE_MSGS_MESSAGE_TANGENTIALSECURITYDISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace naoqi_bridge_msgs
{
template <class ContainerAllocator>
struct TangentialSecurityDistanceRequest_
{
  typedef TangentialSecurityDistanceRequest_<ContainerAllocator> Type;

  TangentialSecurityDistanceRequest_()
    : tangential_distance()  {
    }
  TangentialSecurityDistanceRequest_(const ContainerAllocator& _alloc)
    : tangential_distance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _tangential_distance_type;
  _tangential_distance_type tangential_distance;




  typedef boost::shared_ptr< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TangentialSecurityDistanceRequest_

typedef ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<std::allocator<void> > TangentialSecurityDistanceRequest;

typedef boost::shared_ptr< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest > TangentialSecurityDistanceRequestPtr;
typedef boost::shared_ptr< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest const> TangentialSecurityDistanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace naoqi_bridge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'naoqi_bridge_msgs': ['/home/jose/medeiros_ws/src/naoqi_bridge_msgs/msg', '/home/jose/medeiros_ws/devel/share/naoqi_bridge_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b07653f2626a354d4219619fffc76403";
  }

  static const char* value(const ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb07653f2626a354dULL;
  static const uint64_t static_value2 = 0x4219619fffc76403ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_bridge_msgs/TangentialSecurityDistanceRequest";
  }

  static const char* value(const ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
std_msgs/Float32 tangential_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tangential_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TangentialSecurityDistanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_bridge_msgs::TangentialSecurityDistanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "tangential_distance: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.tangential_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_BRIDGE_MSGS_MESSAGE_TANGENTIALSECURITYDISTANCEREQUEST_H
